version: "3"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins2
    restart: always
    user: root
    volumes:
      - /home/ubuntu/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      TZ: "Asis/Seoul"
