version: "3.7"

services:
  devit-mysql:
    container_name: golearn_db
    build:
      context: ./init
      dockerfile: ./mysql.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_secret
      MYSQL_USER: golearn
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_secret
      MYSQL_DATABASE: golearn
    secrets:
      - mysql_secret
    ports:
      - 3306:3306
    volumes:
      - "mysql_data:/var/lib/mysql"

secrets:
  mysql_secret:
    file: mysql_secret

volumes:
  mysql_data:
